# Streamlit Secrets Configuration
# This file contains API keys for local development
# For production deployment, configure these secrets in Streamlit Cloud

# Mistral API Configuration
MISTRAL_API_KEY = "2B65xYo0m5SCGM7rr7gIQebDF7gmQHqT"

# Groq API Configuration  
GROQ_API_KEY = "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"

# Additional configuration (if needed)
# DATABASE_URL = "your_database_url_here"
# OTHER_SECRET = "your_other_secret_here"

